[0m11:52:23.628580 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023D998AFAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023D998AFE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023D998AFD50>]}


============================== 11:52:23.670744 | 1d0c48c2-34df-4898-9786-41eb620ae0cc ==============================
[0m11:52:23.670744 [info ] [MainThread]: Running with dbt=1.7.9
[0m11:52:23.677766 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\mansi\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init DBT_SNOWFLAKE_PIPELINE', 'send_anonymous_usage_stats': 'True'}
[0m11:52:23.677766 [debug] [MainThread]: Starter project path: C:\Users\mansi\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m11:52:24.211701 [info ] [MainThread]: 
Your new dbt project "DBT_SNOWFLAKE_PIPELINE" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:52:24.227286 [info ] [MainThread]: Setting up your profile.
[0m11:52:24.228688 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m11:52:24.228688 [debug] [MainThread]: Command `dbt init` failed at 11:52:24.228688 after 1.03 seconds
[0m11:52:24.228688 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023D998B84D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023D998B8950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023D998B8510>]}
[0m11:52:24.228688 [debug] [MainThread]: Flushing usage events
[0m23:08:04.743567 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170F7A9D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170F7A8110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170F7A8190>]}


============================== 23:08:04.743567 | bd817f0e-a209-4a43-a8af-a661923735a8 ==============================
[0m23:08:04.743567 [info ] [MainThread]: Running with dbt=1.7.9
[0m23:08:04.760073 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mansi\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:08:04.760073 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\mansi\Documents\DBT-PIPELINE\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:08:04.760073 [debug] [MainThread]: Command `dbt run` failed at 23:08:04.760073 after 0.07 seconds
[0m23:08:04.760073 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021708ACDB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021708ACE710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002170F79D890>]}
[0m23:08:04.760073 [debug] [MainThread]: Flushing usage events
